version: "3"

services:
  mc2:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MEMORY: 4G # majd változtasd 5G -re
      EULA: "TRUE"
      TYPE: "PAPER"
      MOTD: "Deez nuts HAHA"
      OPS: Qkris
      MAX_PLAYERS: 50
      SEED: "-6384763643152943458"
      ONLINE_MODE: FALSE
      SPAWN_PROTECTION: 0
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./plugins:/data/plugins
      - ./data:/data
